# Generated by Django 6.0.7 on 2026-08-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('rauts_id', models.CharField(blank=True, max_length=50, verbose_name='ID персонала в РАУЦ')),
                ('fptitle', models.BooleanField(default=False, verbose_name='Может оформлять документы')),
                ('tptitle', models.BooleanField(default=False, verbose_name='Может подписывать документы')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'История должности',
                'verbose_name_plural': 'История должностей',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1, verbose_name='Пол')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('snils', models.CharField(blank=True, max_length=20, verbose_name='СНИЛС')),
                ('name_latin', models.CharField(blank=True, max_length=100, verbose_name='Имя (латиницей)')),
                ('surname_latin', models.CharField(blank=True, max_length=100, verbose_name='Фамилия (латиницей)')),
                ('employee_id', models.CharField(blank=True, max_length=50, verbose_name='ID сотрудника')),
                ('dcat_id', models.CharField(blank=True, max_length=50, verbose_name='Код профессии РАУЦ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Слушатель',
                'verbose_name_plural': 'Слушатели',
                'ordering': ['surname', 'name'],
            },
        ),
    ]
