# Generated by Django 6.0.7 on 2026-08-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dcat_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код сертификата РАУЦ'),
        ),
    ]
