# Generated by Django 6.0.7 on 2026-08-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_student_dcat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dcat_id',
        ),
    ]
