# Generated by Django 6.0.7 on 2026-09-14 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0013_alter_instructorqualification_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/about/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': "Секция 'О компании'",
                'verbose_name_plural': "Секции 'О компании'",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-идентификатор')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/news/', verbose_name='Изображение')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='landing/partners/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('value', models.CharField(help_text='Например: 1500+', max_length=50, verbose_name='Значение')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('icon', models.CharField(default='📊', max_length=10, verbose_name='Иконка (emoji)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Блок статистики',
                'verbose_name_plural': 'Блоки статистики',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.module', verbose_name='Модуль обучения')),
            ],
            options={
                'verbose_name': 'Рекомендуемый курс',
                'verbose_name_plural': 'Рекомендуемые курсы',
                'ordering': ['order'],
            },
        ),
    ]
