# Generated by Django 6.0.7 on 2026-09-23 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursehighlight',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.module', verbose_name='Модуль обучения'),
        ),
    ]
