# Generated by Django 6.0.7 on 2026-09-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehighlight',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Краткое описание'),
        ),
    ]
