# Generated by Django 6.0.7 on 2026-09-23 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('rauc', 'РАУЦ'), ('frdo', 'ФИС ФРДО')], max_length=10, verbose_name='Тип отчёта')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('excel_file', models.FileField(blank=True, upload_to='reports/excel/', verbose_name='Excel (для проверки)')),
                ('xml_file', models.FileField(blank=True, upload_to='reports/xml/', verbose_name='XML (для отправки)')),
                ('xml_file_hash', models.CharField(blank=True, max_length=64, verbose_name='SHA-256 хеш XML')),
                ('status', models.CharField(choices=[('draft', 'Черновик (есть ошибки)'), ('generated', 'Сформирован (готов к скачиванию)'), ('downloaded', 'Скачан методистом'), ('sent', 'Отправлен в госорган'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='Статус')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата скачивания')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('rejection_date', models.DateField(blank=True, null=True, verbose_name='Дата отклонения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('groups', models.ManyToManyField(blank=True, related_name='regulatory_reports', to='execution.group', verbose_name='Группы')),
            ],
            options={
                'verbose_name': 'Отчёт для госоргана',
                'verbose_name_plural': 'Отчёты для госорганов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Валидна')),
                ('validation_error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('payload', models.JSONField(default=dict, verbose_name='Данные (Payload)')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='execution.certificate')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='execution.enrollment')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reporting.regulatoryreport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.student')),
            ],
            options={
                'verbose_name': 'Строка отчёта',
                'verbose_name_plural': 'Строки отчётов',
                'ordering': ['id'],
            },
        ),
    ]
