# Generated by Django 6.0.7 on 2026-08-12 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('rauc', 'РАУЦ'), ('frdo', 'ФИС ФРДО')], max_length=10, verbose_name='Тип отчёта')),
                ('title', models.CharField(help_text='Например: РАУЦ — НордСтар, Q3 2026', max_length=200, verbose_name='Название')),
                ('period_year', models.PositiveIntegerField(verbose_name='Год отчётного периода')),
                ('period_quarter', models.PositiveSmallIntegerField(blank=True, help_text='1-4 (для ФРДО обязательно, для РАУЦ опционально)', null=True, verbose_name='Квартал')),
                ('report_date', models.DateField(help_text='Дата, на которую сформирован отчёт', verbose_name='Дата отчёта')),
                ('excel_file', models.FileField(blank=True, help_text='Файл для проверки методистом', upload_to='reports/%Y/%m/', verbose_name='Excel файл')),
                ('xml_file', models.FileField(blank=True, help_text='Файл для отправки в госорган', upload_to='reports/%Y/%m/', verbose_name='XML файл')),
                ('xml_file_hash', models.CharField(blank=True, help_text='SHA-256 хеш для проверки целостности', max_length=64, verbose_name='Хеш XML')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('generated', 'Сформирован'), ('downloaded', 'Скачан'), ('sent', 'Отправлен'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='Статус')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата скачивания')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('rejection_reason', models.TextField(blank=True, help_text='Текст с портала госоргана', verbose_name='Причина отклонения')),
                ('rejection_date', models.DateField(blank=True, null=True, verbose_name='Дата отклонения')),
                ('comment', models.TextField(blank=True, help_text='Внутренний комментарий методиста', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validation_overrides', models.JSONField(blank=True, default=list, help_text='Список ID объектов, которые методист решил пропустить', verbose_name='Исключения валидации')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('groups', models.ManyToManyField(blank=True, help_text='Группы, включённые в отчёт', related_name='regulatory_reports', to='execution.group', verbose_name='Группы')),
                ('replaces', models.ForeignKey(blank=True, help_text='Предыдущая версия отчёта (если это корректирующий)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_by', to='reporting.regulatoryreport', verbose_name='Заменяет')),
            ],
            options={
                'verbose_name': 'Отчёт для госоргана',
                'verbose_name_plural': 'Отчёты для госорганов',
                'ordering': ['-created_at'],
            },
        ),
    ]
