# Generated by Django 6.0.7 on 2026-08-12 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_initial'),
        ('people', '0002_initial'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulatoryreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отчёт для госоргана (Шапка)', 'verbose_name_plural': 'Отчёты для госорганов'},
        ),
        migrations.RemoveField(
            model_name='regulatoryreport',
            name='validation_overrides',
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Внутренний комментарий'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_regulatory_reports', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='excel_file',
            field=models.FileField(blank=True, upload_to='reports/%Y/%m/', verbose_name='Excel файл (для проверки)'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, данные которых включены в отчёт', related_name='regulatory_reports', to='execution.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='period_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год отчётного периода'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_by', to='reporting.regulatoryreport', verbose_name='Заменяет (корректирующий отчёт)'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='report_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата отчёта'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='title',
            field=models.CharField(help_text='Например: ФРДО — 3 квартал 2026', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='xml_file',
            field=models.FileField(blank=True, upload_to='reports/%Y/%m/', verbose_name='XML файл (для отправки)'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='xml_file_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='SHA-256 хеш XML'),
        ),
        migrations.CreateModel(
            name='RegulatoryReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Прошёл валидацию')),
                ('validation_error', models.TextField(blank=True, help_text='Почему эта строка не может попасть в отчёт', verbose_name='Ошибка валидации')),
                ('payload', models.JSONField(default=dict, help_text='Словарь с данными, готовыми для выгрузки в Excel/XML', verbose_name='Данные строки отчёта (Payload)')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='execution.certificate', verbose_name='Сертификат/Удостоверение')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='execution.enrollment', verbose_name='Зачисление')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reporting.regulatoryreport', verbose_name='Отчёт')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.student', verbose_name='Слушатель')),
            ],
            options={
                'verbose_name': 'Строка отчёта',
                'verbose_name_plural': 'Строки отчётов',
                'ordering': ['id'],
            },
        ),
    ]
