# Generated by Django 6.0.7 on 2026-08-12 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_initial'),
        ('people', '0002_initial'),
        ('reporting', '0002_alter_regulatoryreport_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulatoryreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отчёт для госоргана', 'verbose_name_plural': 'Отчёты для госорганов'},
        ),
        migrations.RemoveField(
            model_name='regulatoryreport',
            name='period_quarter',
        ),
        migrations.RemoveField(
            model_name='regulatoryreport',
            name='period_year',
        ),
        migrations.RemoveField(
            model_name='regulatoryreport',
            name='replaces',
        ),
        migrations.RemoveField(
            model_name='regulatoryreport',
            name='report_date',
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='excel_file',
            field=models.FileField(blank=True, upload_to='reports/excel/', verbose_name='Excel (для проверки)'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='regulatory_reports', to='execution.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отклонения'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик (есть ошибки)'), ('generated', 'Сформирован (готов к скачиванию)'), ('downloaded', 'Скачан методистом'), ('sent', 'Отправлен в госорган'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='xml_file',
            field=models.FileField(blank=True, upload_to='reports/xml/', verbose_name='XML (для отправки)'),
        ),
        migrations.AlterField(
            model_name='regulatoryreportitem',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='execution.certificate'),
        ),
        migrations.AlterField(
            model_name='regulatoryreportitem',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='execution.enrollment'),
        ),
        migrations.AlterField(
            model_name='regulatoryreportitem',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Валидна'),
        ),
        migrations.AlterField(
            model_name='regulatoryreportitem',
            name='payload',
            field=models.JSONField(default=dict, verbose_name='Данные (Payload)'),
        ),
        migrations.AlterField(
            model_name='regulatoryreportitem',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reporting.regulatoryreport'),
        ),
        migrations.AlterField(
            model_name='regulatoryreportitem',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.student'),
        ),
        migrations.AlterField(
            model_name='regulatoryreportitem',
            name='validation_error',
            field=models.TextField(blank=True, verbose_name='Ошибка'),
        ),
    ]
