# Generated by Django 6.0.7 on 2026-08-12 01:45

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('test', 'Тестирование'), ('practice', 'Практическое задание'), ('oral', 'Устный опрос'), ('exam', 'Итоговый экзамен'), ('attendance', 'Посещаемость')], default='test', max_length=20, verbose_name='Тип аттестации')),
                ('score', models.IntegerField(blank=True, help_text='Для numeric: 4 или 5. Для binary: 0 или 1', null=True, verbose_name='Балл')),
                ('passed', models.BooleanField(default=False, help_text='Вычисляется автоматически на основе требований раздела', verbose_name='Зачтено')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, help_text='1 — первая сдача, 2 — пересдача и т.д.', verbose_name='Номер попытки')),
                ('assessment_date', models.DateField(blank=True, null=True, verbose_name='Дата аттестации')),
                ('notes', models.TextField(blank=True, help_text="Например: 'пересдача', 'апелляция', 'досрочно'", verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['enrollment', 'section__stage__order', 'section__order', 'attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('certificate', 'Сертификат'), ('witness', 'Свидетельство'), ('diploma', 'Диплом'), ('reference', 'Справка'), ('credential', 'Удостоверение')], default='credential', max_length=20, verbose_name='Тип документа')),
                ('number', models.CharField(help_text='Например: 001.2026-СЗ/3-001-1', max_length=50, unique=True, verbose_name='Номер')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('student_full_name', models.CharField(max_length=200, verbose_name='ФИО слушателя')),
                ('student_profession', models.CharField(blank=True, max_length=200, verbose_name='Специальность')),
                ('module_title', models.CharField(max_length=300, verbose_name='Название модуля')),
                ('module_code', models.CharField(max_length=50, verbose_name='Код модуля')),
                ('aircraft_type', models.CharField(blank=True, max_length=100, verbose_name='Тип ВС')),
                ('total_hours', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Всего часов')),
                ('qualification', models.CharField(blank=True, help_text="Например: 'Пилот' или 'Бортпроводник'", max_length=200, verbose_name='Квалификация')),
                ('pdf_file', models.FileField(blank=True, upload_to='certificates/%Y/%m/', verbose_name='PDF файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Свидетельство/Сертификат',
                'verbose_name_plural': 'Свидетельства/Сертификаты',
                'ordering': ['-issue_date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_group', models.PositiveIntegerField(verbose_name='Порядковый номер в группе')),
                ('order_out_number', models.CharField(blank=True, max_length=50, verbose_name="Номер приказа об отчислении. Если завершен успешно в конце 'ОК', если нет - 'ОТ'")),
                ('order_out_date', models.DateField(blank=True, null=True, verbose_name='Дата приказа об отчислении')),
                ('status', models.CharField(choices=[('enrolled', 'Зачислен'), ('in_progress', 'Обучается'), ('completed', 'Успешно завершен'), ('failed', 'Не завершен'), ('dismissed', 'Отчислен'), ('academic_leave', 'Академический отпуск'), ('partial', 'Частично прослушал'), ('absent', 'Не явился')], default='enrolled', max_length=20, verbose_name='Статус')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата отчисления')),
                ('dismissal_reason', models.TextField(blank=True, verbose_name='Причина отчисления')),
                ('final_result', models.CharField(blank=True, help_text='Заполняется автоматически: passed/failed', max_length=20, verbose_name='Итоговый результат')),
                ('total_hours_completed', models.DecimalField(decimal_places=1, default=0, help_text='Сумма часов по сданным разделам', max_digits=6, verbose_name='Освоено часов')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
                'ordering': ['group', 'number_in_group'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_number', models.CharField(help_text='123.2026', max_length=30, verbose_name='Номер группы')),
                ('application', models.CharField(help_text='СЗ/3-123', max_length=30, verbose_name='Номер заявки')),
                ('order_in_number', models.CharField(blank=True, max_length=50, verbose_name='Номер приказа о зачислении')),
                ('order_in_date', models.DateField(blank=True, null=True, verbose_name='Дата приказа о зачислении')),
                ('start_date', models.DateField(verbose_name='Дата начала СДО')),
                ('start_face_to_face', models.DateField(blank=True, null=True, verbose_name='Дата начала очных занятий')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата окончания')),
                ('is_sdo', models.BooleanField(default=False, verbose_name='Только СДО (без очных занятий)')),
                ('start_time_default', models.TimeField(default=datetime.time(9, 0), help_text='Время начала первого занятия в день (например, 09:00 или 14:00)', verbose_name='Время начала очных занятий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('enrolling', 'Набор'), ('in_progress', 'Обучение'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('deadline', models.DateField(blank=True, help_text='Для СДО: крайняя дата', null=True, verbose_name='Дедлайн выполнения')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('session_type', models.CharField(help_text='sdo, sim, base-N', max_length=50, verbose_name='Тип занятия')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'Идет'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Детализация времени / Примечание')),
            ],
            options={
                'verbose_name': 'Занятие расписания',
                'verbose_name_plural': 'Расписание',
                'ordering': ['date', 'start_time', 'section__order', 'subsection__order'],
            },
        ),
    ]
