# Generated by Django 6.0.7 on 2026-08-12 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
        ('people', '0001_initial'),
        ('references', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_assessments', to='people.staff', verbose_name='Принял аттестацию'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='training.section', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='license',
            field=models.ForeignKey(blank=True, help_text='Государственная лицензия, на основании которой выдан документ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='references.license', verbose_name='Лицензия АУЦ'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.student', verbose_name='Слушатель'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='execution.enrollment', verbose_name='Зачисление'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='execution.enrollment', verbose_name='Зачисление'),
        ),
        migrations.AddField(
            model_name='group',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to='people.staff', verbose_name='Создал сотрудник'),
        ),
        migrations.AddField(
            model_name='group',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_groups', to='people.staff', verbose_name='Куратор группы'),
        ),
        migrations.AddField(
            model_name='group',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signing_executive', to='people.staff', verbose_name='Подписывающий руководитель'),
        ),
        migrations.AddField(
            model_name='group',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.location', verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='group',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.module', verbose_name='Модуль'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.classroom', verbose_name='Аудитория/Тренажёр'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='execution.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.staff', verbose_name='Преподаватель/Инструктор'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='training.section', verbose_name='Дисциплина'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='training.subsection', verbose_name='Тема/Сессия'),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('enrollment', 'section', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('group', 'number_in_group')},
        ),
    ]
