# Generated by Django 6.0.7 on 2026-08-17 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_initial'),
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_groups', to='people.staff', verbose_name='Методист образовательного процесса'),
        ),
    ]
