# Generated by Django 6.0.7 on 2026-09-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_alter_compliancelog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='actual_completion_date',
            field=models.DateField(blank=True, help_text='Дата последнего занятия/экзамена. Используется в сертификатах и ЗНТ. Можно редактировать вручную.', null=True, verbose_name='Фактическая дата завершения обучения'),
        ),
    ]
