# Generated by Django 6.0.7 on 2026-08-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_alter_group_curator_alter_group_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('enrolling', 'Набор'), ('in_progress', 'Обучение'), ('completed', 'Завершена'), ('archived', 'Архив'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
