# Generated by Django 6.0.7 on 2026-08-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_alter_group_status'),
        ('people', '0004_remove_student_dcat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualStudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала ИУП')),
                ('end_date', models.DateField(verbose_name='Дата окончания ИУП')),
                ('start_face_to_face', models.DateField(blank=True, null=True, verbose_name='Дата начала очных занятий ИУП')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='active', max_length=20, verbose_name='Статус')),
                ('reason', models.TextField(blank=True, help_text='Например: болезнь, командировка, семейные обстоятельства', verbose_name='Причина назначения ИУП')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.staff', verbose_name='Создал')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.group', verbose_name='Группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Индивидуальный учебный план',
                'verbose_name_plural': 'Индивидуальные учебные планы',
                'ordering': ['-created_at'],
            },
        ),
    ]
