# Generated by Django 6.0.7 on 2026-08-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_individualstudyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualstudyplan',
            name='schedule_data',
            field=models.JSONField(blank=True, help_text='Массив занятий с индивидуальными датами, инструкторами и аудиториями', null=True, verbose_name='Расписание ИУП (JSON)'),
        ),
        migrations.AddField(
            model_name='individualstudyplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='individualstudyplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
