# Generated by Django 6.0.7 on 2026-08-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0007_individualstudyplan_schedule_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualstudyplan',
            name='reason',
            field=models.TextField(blank=True, choices=[('business', 'Производственная необходимость'), ('disease', 'Болезнь'), ('vacation', 'Отпуск'), ('family', 'Семейные обстоятельства')], verbose_name='Причина назначения ИУП'),
        ),
    ]
