# Generated by Django 6.0.7 on 2026-08-26 19:33

from django.db import migrations, models

def merge_application_into_assigned_number(apps, schema_editor):
    Group = apps.get_model('execution', 'Group')
    for group in Group.objects.all():
        # Если у группы есть application, добавляем его к assigned_number
        if group.application:
            # Проверяем, не содержит ли уже assigned_number application
            if group.application not in group.assigned_number:
                group.assigned_number = f"{group.assigned_number}-{group.application}"
                group.save()

def reverse_merge(apps, schema_editor):
    # Обратная операция не выполняется, так как мы удаляем поле
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0008_alter_individualstudyplan_reason'),
    ]

    operations = [
        # Сначала расширяем поле assigned_number
        migrations.AlterField(
            model_name='group',
            name='assigned_number',
            field=models.CharField(help_text='Формат: 001.2026-СЗ/23-234', max_length=70, unique=True, verbose_name='Номер группы'),
        ),
        # Добавляем data migration
        migrations.RunPython(merge_application_into_assigned_number, reverse_merge),
        # Удаляем поле application
        migrations.RemoveField(
            model_name='group',
            name='application',
        ),
    ]


