# Generated by Django 6.0.7 on 2026-08-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0009_remove_group_application_alter_group_assigned_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='application',
            field=models.CharField(blank=True, help_text='Заполняется вручную, используется только в отчётах РАУЦ и ФРДО', max_length=30, verbose_name='Номер заявки (для РАУЦ/ФРДО)'),
        ),
    ]
