# Generated by Django 6.0.7 on 2026-08-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0010_group_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Заполняется вручную, используется только в отчётах ФРДО. Формат: 001.2026', max_length=30, verbose_name='Серия документа (для ФРДО)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='application',
            field=models.CharField(blank=True, help_text='Заполняется вручную, используется только в отчётах ФРДО. Формат: СЗ/ХХ-123', max_length=30, verbose_name='Номер документа (для ФРДО)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='assigned_number',
            field=models.CharField(help_text='Формат: 001.2026-СЗ/ХХ-234', max_length=70, unique=True, verbose_name='Номер группы'),
        ),
    ]
