# Generated by Django 6.0.7 on 2026-08-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0011_group_serial_number_alter_group_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='application',
            field=models.CharField(blank=True, help_text='Заполняется вручную, используется только в отчётах ФРДО. Формат: СЗ/ХХ-123', max_length=30, verbose_name='Заявка - номер документа (для ФРДО)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Заполняется вручную, используется только в отчётах ФРДО. Формат: 001.2026', max_length=30, verbose_name='Номер группы по реестру (серия документа для ФРДО)'),
        ),
    ]
