# Generated by Django 6.0.7 on 2026-08-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0012_alter_group_application_alter_group_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='assigned_number',
            field=models.CharField(help_text='Формат: 001.2026-СЗ/ХХ-234', max_length=70, unique=True, verbose_name='Номер группы (Номер по реестру и Заявка)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Заполняется вручную, используется только в отчётах ФРДО. Формат: 001.2026', max_length=30, verbose_name='Номер по реестру (серия документа для ФРДО)'),
        ),
    ]
