# Generated by Django 6.0.7 on 2026-08-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0013_alter_group_assigned_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='assigned_number',
            field=models.CharField(help_text='Номер по реестру + Заявка. Формат: 001.2026-СЗ/ХХ-234', max_length=70, unique=True, verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='order_in_number',
            field=models.CharField(blank=True, help_text='Номер группы + З. Формат: 001.2026-СЗ/ХХ-234-З', max_length=50, verbose_name='Номер приказа о зачислении'),
        ),
    ]
