# Generated by Django 6.0.7 on 2026-09-07 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0015_alter_group_application_alter_group_serial_number'),
        ('people', '0004_remove_student_dcat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_schedule_items', to='people.staff', verbose_name='Кто подтвердил'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Преподаватель подтвердил факт проведения занятия', verbose_name='Подтверждено преподавателем'),
        ),
    ]
