# Generated by Django 6.0.7 on 2026-09-10 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0016_scheduleitem_confirmed_at_scheduleitem_confirmed_by_and_more'),
        ('people', '0004_remove_student_dcat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitem',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Ставится True при финальном подтверждении инструктором.', verbose_name='Занятие завершено и закрыто'),
        ),
        migrations.CreateModel(
            name='ComplianceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('instructor_familiarized', 'Инструктор ознакомлен с планом занятия'), ('grades_submitted', 'Инструктор сохранил/выставил оценки'), ('lesson_completed', 'Инструктор подтвердил проведение занятия'), ('methodist_corrected', 'Методист внес исправления в журнал')], max_length=30, verbose_name='Тип действия')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время фиксации (сервер)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Для аудита безопасности', null=True, verbose_name='IP-адрес')),
                ('notes', models.TextField(blank=True, verbose_name='Служебная отметка')),
                ('schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_logs', to='execution.scheduleitem', verbose_name='Конкретное занятие')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.staff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись в журнале подтверждений',
                'verbose_name_plural': 'Журнал подтверждений и аудита',
                'ordering': ['-timestamp'],
            },
        ),
    ]
