# Generated by Django 6.0.7 on 2026-09-10 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0017_remove_scheduleitem_confirmed_at_and_more'),
        ('people', '0004_remove_student_dcat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancelog',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_logs', to='execution.enrollment', verbose_name='Зачисление в группу'),
        ),
        migrations.AddField(
            model_name='compliancelog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='compliancelog',
            name='action_type',
            field=models.CharField(choices=[('instructor_familiarized', 'Инструктор ознакомлен с планом занятия'), ('grades_submitted', 'Инструктор сохранил/выставил оценки'), ('lesson_completed', 'Инструктор подтвердил проведение занятия'), ('methodist_corrected', 'Методист внес исправления в журнал'), ('student_attendance_confirmed', 'Студент подтвердил присутствие'), ('student_safety_ack', 'Студент ознакомлен с ТБ'), ('student_grade_ack', 'Студент ознакомлен с оценкой'), ('certificate_received', 'Студент подтвердил получение документа')], max_length=30, verbose_name='Тип действия'),
        ),
    ]
