# Generated by Django 6.0.7 on 2026-09-11 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0018_compliancelog_enrollment_compliancelog_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancelog',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_logs', to='execution.assessment', verbose_name='Оценка (для ознакомления)'),
        ),
        migrations.AddField(
            model_name='compliancelog',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_logs', to='execution.certificate', verbose_name='Документ (для получения)'),
        ),
        migrations.AlterField(
            model_name='compliancelog',
            name='action_type',
            field=models.CharField(choices=[('instructor_familiarized', 'Инструктор ознакомлен с планом занятия'), ('grades_submitted', 'Инструктор сохранил/выставил оценки'), ('lesson_completed', 'Инструктор подтвердил проведение занятия'), ('methodist_corrected', 'Методист внес исправления в журнал'), ('student_safety_ack', 'Инструктаж по ОТ, ТБ, ППБ + согласие на обработку ПД + ознакомление с порядком'), ('student_attendance_confirmed', 'Подтверждение присутствия на занятии'), ('student_grade_ack', 'Ознакомление с оценкой'), ('certificate_received', 'Получение документа (Удостоверение/Свидетельство/ЗНТ)')], max_length=30, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='compliancelog',
            name='schedule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_logs', to='execution.scheduleitem', verbose_name='Занятие (для посещаемости)'),
        ),
    ]
