# Generated by Django 6.0.7 on 2026-09-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0019_compliancelog_assessment_compliancelog_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancelog',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_logs', to='execution.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='compliancelog',
            name='action_type',
            field=models.CharField(choices=[('instructor_familiarized', 'Инструктор ознакомлен с планом занятия'), ('instructor_schedule_ack', 'Инструктор ознакомлен с учебным расписанием'), ('instructor_briefing_done', 'Инструктор провел инструктаж для студента'), ('lesson_completed', 'Инструктор подтвердил проведение занятия'), ('grades_submitted', 'Инструктор сохранил/выставил оценки'), ('methodist_corrected', 'Методист внес исправления в журнал'), ('student_schedule_ack', 'Ознакомление с учебным расписанием'), ('student_safety_ack', 'Инструктаж по ОТ, ТБ, ППБ + согласие на обработку ПД + ознакомление с порядком'), ('student_attendance_confirmed', 'Подтверждение присутствия на занятии'), ('student_grade_ack', 'Ознакомление с оценкой'), ('certificate_received', 'Получение документа (Удостоверение/Свидетельство/ЗНТ)'), ('director_schedule_approved', 'Директор утвердил расписание')], max_length=30, verbose_name='Тип действия'),
        ),
    ]
