# Generated by Django 6.0.7 on 2026-08-12 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип ВС')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Тип ВС',
                'verbose_name_plural': 'Типы ВС',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Страна')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='Код страны по ОКСМ')),
            ],
            options={
                'verbose_name': 'Гражданство',
                'verbose_name_plural': 'Гражданство',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ', models.CharField(max_length=200, verbose_name='Название органа')),
                ('license_number', models.CharField(max_length=100, verbose_name='Номер лицензии')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Государственная лицензия',
                'verbose_name_plural': 'Государственные лицензии',
                'ordering': ['organ'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='DME', max_length=10, verbose_name='Код города IATA')),
                ('full_name', models.CharField(blank=True, help_text='Домодедово', max_length=50, null=True, verbose_name='Географическое название')),
                ('addr', models.PositiveIntegerField(blank=True, null=True, verbose_name='Код РАУЦ (Место проведения)')),
                ('dept', models.PositiveIntegerField(blank=True, null=True, verbose_name='Код РАУЦ (Филиал)')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название должности')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Должность сотрудника',
                'verbose_name_plural': 'Должности сотрудников',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название профессии')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Профессия слушателя',
                'verbose_name_plural': 'Профессии слушателей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.location', verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(blank=True, help_text='Если не заполнен, используется адрес организации', max_length=300, null=True, verbose_name='Фактический адрес')),
                ('audience', models.CharField(blank=True, max_length=100, verbose_name='Аудитория')),
                ('contact_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.staff', verbose_name='Ответственный сотрудник')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.location', verbose_name='Местоположение')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Аудитория/Тренажёр',
                'verbose_name_plural': 'Аудитории/Тренажёры',
                'ordering': ['title'],
            },
        ),
    ]
