# Generated by Django 6.0.7 on 2026-08-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='addr',
            field=models.CharField(blank=True, help_text='Например: 174', max_length=10, null=True, verbose_name='Код РАУЦ (Место проведения)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='dept',
            field=models.CharField(blank=True, help_text='Например: 37', max_length=10, null=True, verbose_name='Код РАУЦ (Филиал)'),
        ),
    ]
