# Generated by Django 6.0.7 on 2026-09-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_alter_location_addr_alter_location_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='timezone',
            field=models.CharField(default='Europe/Moscow', help_text='Например: Asia/Krasnoyarsk, Europe/Ulyanovsk', max_length=50, verbose_name='Часовой пояс'),
        ),
    ]
