# Generated by Django 6.0.7 on 2026-09-23 08:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frdo_template_type', models.CharField(choices=[('flight_attendant', 'Бортпроводники (Проф. обучение)'), ('pilot_engineer', 'Пилоты и инженеры (Доп. проф. программа)')], default='flight_attendant', help_text='Определяет структуру колонок и названия полей в отчёте ФРДО', max_length=20, verbose_name='Шаблон отчёта ФРДО')),
                ('form_of_education', models.CharField(blank=True, choices=[('Очная', 'Очная'), ('Заочная', 'Заочная'), ('Очно-заочная (вечерняя)', 'Очно-заочная (вечерняя)'), ('Экстернат', 'Экстернат')], help_text='Форма обучения для отчётов ФРДО и сертификатов', max_length=50, verbose_name='Форма обучения')),
                ('title', models.TextField(verbose_name='Название программы')),
                ('prog_id', models.CharField(blank=True, max_length=50, verbose_name='ID программы')),
                ('company_code', models.CharField(blank=True, max_length=50, verbose_name='Код программы')),
                ('approved', models.CharField(blank=True, max_length=300, null=True, verbose_name='Утверждена государственным органом')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('default_certificate_type', models.CharField(choices=[('certificate', 'Сертификат'), ('witness', 'Свидетельство'), ('diploma', 'Диплом'), ('reference', 'Справка'), ('credential', 'Удостоверение')], default='credential', help_text='Тип документа, который будет автоматически присваиваться при выдаче сертификата для этой программы', max_length=20, verbose_name='Тип документа по умолчанию')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': 'Программы обучения',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('code', models.CharField(blank=True, help_text='Например: DG, ASP-W, ASP-L, FFS', max_length=50, verbose_name='Код предмета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Предмет / Дисциплина',
                'verbose_name_plural': 'Предметы / Дисциплины',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название модуля')),
                ('mod_id', models.CharField(blank=True, help_text='Например: 8304 или 8886 (из справочника РАУЦ)', max_length=50, verbose_name='ID модуля РАУЦ')),
                ('code', models.CharField(blank=True, help_text='Например: ППП.АУЦ.02-М.1', max_length=50, verbose_name='Код модуля')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Плановые часы')),
                ('attachment_number', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Номер приложения для выписки сертификата')),
                ('certificate_template', models.CharField(blank=True, help_text='Путь к шаблону, напр.: docs/certificate/course_1/certificate_c1_m1_batch.html', max_length=255, verbose_name='Шаблон сертификата')),
                ('validity_period', models.IntegerField(blank=True, help_text='Период повторения подготовки в месяцах. Например: 12 (1 год), 24 (2 года), 36 (3 года). Оставьте пустым, если срок не ограничен.', null=True, verbose_name='Срок действия (месяцев)')),
                ('aircraft_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.aircrafttype', verbose_name='Тип ВС')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='training.course', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['course', 'mod_id'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='training.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название раздела/дисциплины')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Продолжительность (часов)')),
                ('grade_type', models.CharField(choices=[('numeric', 'Числовая'), ('binary', 'Зачтено/Не зачтено'), ('none', 'Без оценки')], default='none', max_length=10, verbose_name='Тип оценки')),
                ('min_score', models.IntegerField(blank=True, null=True, verbose_name='Минимальный балл')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('detail', models.CharField(blank=True, choices=[('sdo', 'СДО'), ('sim', 'Тренажер'), ('base-1', '1 урок'), ('base-2', '2 урока'), ('base-3', '3 урока'), ('base-4', '4 урока'), ('base-5', '5 уроков'), ('base-6', '6 уроков'), ('base-7', '7 уроков'), ('base-8', '8 уроков'), ('base-9', '9 уроков'), ('none', 'Не задано')], max_length=50, null=True, verbose_name='Тип расписания')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='training.stage', verbose_name='Этап')),
                ('subject', models.ForeignKey(blank=True, help_text='К какому предмету относится этот раздел (для допусков инструкторов). Пока необязательно.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.subject', verbose_name='Предмет / Дисциплина')),
            ],
            options={
                'verbose_name': 'Раздел/Дисциплина',
                'verbose_name_plural': 'Разделы/Дисциплины',
                'ordering': ['stage', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название подраздела/сессии')),
                ('detail', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип детализации')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Продолжительность (часов)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='training.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Подраздел/Сессия',
                'verbose_name_plural': 'Подразделы/Сессии',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='InstructorQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('CLASS', 'Аудиторные занятия'), ('FFS', 'Комплексный тренажер (FFS)'), ('FTD', 'Процедурный тренажер (FTD)'), ('CBT', 'Компьютерное обучение (CBT)'), ('ON_JOB', 'Стажировка на рабочем месте'), ('VR', 'VR-тренировки'), ('ASP_W', 'АСП вода'), ('ASP_L', 'АСП суша')], default='CLASS', help_text='На каком оборудовании/формате может преподавать', max_length=20, verbose_name='Тип средства обучения')),
                ('certificate_number', models.CharField(blank=True, help_text='Например: № 123-А от 01.01.2024', max_length=100, null=True, verbose_name='Номер сертификата / допуска')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('validity_months', models.PositiveIntegerField(default=24, help_text='Через сколько месяцев нужно продление', verbose_name='Срок действия (месяцев)')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку при досрочном аннулировании', verbose_name='Допуск активен')),
                ('waiver_notes', models.TextField(blank=True, help_text="Например: 'Временное продление по распоряжению Росавиации до 01.12.2024'", null=True, verbose_name='Примечание / Временное разрешение')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='people.staff', verbose_name='Сотрудник (Инструктор)')),
                ('subject', models.ForeignKey(help_text='К какому предмету допущен инструктор', on_delete=django.db.models.deletion.CASCADE, to='training.subject', verbose_name='Предмет / Дисциплина')),
            ],
            options={
                'verbose_name': 'Допуск инструктора',
                'verbose_name_plural': 'Допуски инструкторов',
                'ordering': ['staff', 'subject'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('staff', 'subject', 'device_type'), name='unique_active_qualification')],
            },
        ),
    ]
