# Generated by Django 6.0.7 on 2026-08-12 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название программы')),
                ('prog_id', models.CharField(blank=True, max_length=50, verbose_name='ID программы')),
                ('company_code', models.CharField(blank=True, max_length=50, verbose_name='Код программы')),
                ('approved', models.CharField(blank=True, max_length=300, null=True, verbose_name='Утверждена государственным органом')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='Дата утверждения')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': 'Программы обучения',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название модуля')),
                ('mod_id', models.CharField(blank=True, max_length=50, verbose_name='ID модуля РАУЦ')),
                ('code', models.CharField(blank=True, help_text='ППП.АУЦ.ХХ-М.Х', max_length=50, verbose_name='Код модуля')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Плановые часы')),
                ('attachment_number', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Номер приложения для выписки сертификата')),
                ('aircraft_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.aircrafttype', verbose_name='Тип ВС')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='training.course', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['course', 'mod_id'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='training.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название раздела/дисциплины')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Продолжительность (часов)')),
                ('grade_type', models.CharField(choices=[('numeric', 'Числовая'), ('binary', 'Зачтено/Не зачтено'), ('none', 'Без оценки')], default='none', max_length=10, verbose_name='Тип оценки')),
                ('min_score', models.IntegerField(blank=True, null=True, verbose_name='Минимальный балл')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('detail', models.CharField(blank=True, choices=[('sdo', 'СДО'), ('sim', 'Тренажер'), ('base-1', '1 урок'), ('base-2', '2 урока'), ('base-3', '3 урока'), ('base-4', '4 урока'), ('base-5', '5 уроков'), ('base-6', '6 уроков'), ('base-7', '7 уроков'), ('base-8', '8 уроков'), ('base-9', '9 уроков'), ('none', 'Не задано')], max_length=50, null=True, verbose_name='Тип расписания')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='training.stage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Раздел/Дисциплина',
                'verbose_name_plural': 'Разделы/Дисциплины',
                'ordering': ['stage', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название подраздела/сессии')),
                ('detail', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип детализации')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Продолжительность (часов)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='training.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Подраздел/Сессия',
                'verbose_name_plural': 'Подразделы/Сессии',
                'ordering': ['section', 'order'],
            },
        ),
    ]
