# Generated by Django 6.0.7 on 2026-08-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='approval_date',
            field=models.CharField(blank=True, help_text='Напр.: 01.01.2020', max_length=50, verbose_name='Дата утверждения программы'),
        ),
        migrations.AddField(
            model_name='module',
            name='approval_organ',
            field=models.CharField(blank=True, help_text='Напр.: Федеральным агентством воздушного транспорта', max_length=255, verbose_name='Орган, утвердивший программу'),
        ),
        migrations.AddField(
            model_name='module',
            name='certificate_template',
            field=models.CharField(blank=True, help_text='Путь к шаблону, напр.: docs/certificate/course_1/certificate_c1_m1_batch.html', max_length=255, verbose_name='Шаблон сертификата'),
        ),
        migrations.AddField(
            model_name='module',
            name='prog_id',
            field=models.CharField(blank=True, help_text='Например: 9872 или 10520 (из справочника РАУЦ)', max_length=50, verbose_name='ID программы РАУЦ'),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(blank=True, help_text='Например: ППП.АУЦ.02-М.1', max_length=50, verbose_name='Код модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='mod_id',
            field=models.CharField(blank=True, help_text='Например: 8304 или 8886 (из справочника РАУЦ)', max_length=50, verbose_name='ID модуля РАУЦ'),
        ),
    ]
