# Generated by Django 6.0.7 on 2026-08-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_module_approval_date_module_approval_organ_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='module',
            name='approval_organ',
        ),
    ]
