# Generated by Django 6.0.7 on 2026-08-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_module_approval_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='prog_id',
        ),
    ]
