# Generated by Django 6.0.7 on 2026-08-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_remove_module_prog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='default_certificate_type',
            field=models.CharField(choices=[('certificate', 'Сертификат'), ('witness', 'Свидетельство'), ('diploma', 'Диплом'), ('reference', 'Справка'), ('credential', 'Удостоверение')], default='credential', help_text='Тип документа, который будет автоматически присваиваться при выдаче сертификата для этой программы', max_length=20, verbose_name='Тип документа по умолчанию'),
        ),
    ]
