# Generated by Django 6.0.7 on 2026-08-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_course_default_certificate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='validity_period',
            field=models.IntegerField(blank=True, help_text='Период повторения подготовки в месяцах. Например: 12 (1 год), 24 (2 года), 36 (3 года). Оставьте пустым, если срок не ограничен.', null=True, verbose_name='Срок действия (месяцев)'),
        ),
    ]
