# Generated by Django 6.0.7 on 2026-08-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_module_validity_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='form_of_education',
            field=models.CharField(blank=True, choices=[('Очная', 'Очная'), ('Заочная', 'Заочная'), ('Очно-заочная (вечерняя)', 'Очно-заочная (вечерняя)'), ('Экстернат', 'Экстернат')], help_text='Форма обучения для отчётов ФРДО и сертификатов', max_length=50, verbose_name='Форма обучения'),
        ),
    ]
