# Generated by Django 6.0.7 on 2026-08-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_course_form_of_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='frdo_template_type',
            field=models.CharField(choices=[('flight_attendant', 'Бортпроводники (Проф. обучение)'), ('pilot_engineer', 'Пилоты и инженеры (Доп. проф. программа)')], default='flight_attendant', help_text='Определяет структуру колонок и названия полей в отчёте ФРДО', max_length=20, verbose_name='Шаблон отчёта ФРДО'),
        ),
    ]
