# Generated by Django 6.0.7 on 2026-08-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_alter_course_frdo_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='frdo_template_type',
            field=models.CharField(choices=[('flight_attendant', 'Бортпроводники (Проф. обучение)'), ('pilot', 'Пилоты (Доп. проф. программа)'), ('engineer', 'Инженеры (Доп. проф. программа)'), ('representative', 'Представители (Повышение квалификации)'), ('pilot_engineer', 'Пилоты и инженеры (Устаревшее)')], default='flight_attendant', help_text='Определяет структуру колонок и названия полей в отчёте ФРДО', max_length=20, verbose_name='Шаблон отчёта ФРДО'),
        ),
    ]
