# Generated by Django 6.0.7 on 2026-09-05 05:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_remove_student_dcat_id'),
        ('training', '0011_alter_course_frdo_template_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('code', models.CharField(blank=True, help_text='Например: DG, ASP-W, ASP-L, FFS', max_length=50, verbose_name='Код предмета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Предмет / Дисциплина',
                'verbose_name_plural': 'Предметы / Дисциплины',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='К какому предмету относится этот раздел (для допусков инструкторов). Пока необязательно.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.subject', verbose_name='Предмет / Дисциплина'),
        ),
        migrations.CreateModel(
            name='InstructorQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('CLASS', 'Аудиторные занятия'), ('FFS', 'Полнокомплексный тренажер (FFS)'), ('FTD', 'Тренажер (FTD)'), ('CBT', 'Компьютерное обучение (CBT)'), ('ON_JOB', 'Стажировка на рабочем месте'), ('VR', 'VR-тренировки'), ('ASP_W', 'АСП вода'), ('ASP_L', 'АСП суша')], default='CLASS', help_text='На каком оборудовании/формате может преподавать', max_length=20, verbose_name='Тип средства обучения')),
                ('certificate_number', models.CharField(blank=True, help_text='Например: № 123-А от 01.01.2024', max_length=100, null=True, verbose_name='Номер сертификата / допуска')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('validity_months', models.PositiveIntegerField(default=24, help_text='Через сколько месяцев нужно продление', verbose_name='Срок действия (месяцев)')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку при досрочном аннулировании', verbose_name='Допуск активен')),
                ('waiver_notes', models.TextField(blank=True, help_text="Например: 'Временное продление по распоряжению Росавиации до 01.12.2024'", null=True, verbose_name='Примечание / Временное разрешение')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='people.staff', verbose_name='Сотрудник (Инструктор)')),
                ('subject', models.ForeignKey(help_text='К какому предмету допущен инструктор', on_delete=django.db.models.deletion.CASCADE, to='training.subject', verbose_name='Предмет / Дисциплина')),
            ],
            options={
                'verbose_name': 'Допуск инструктора',
                'verbose_name_plural': 'Допуски инструкторов',
                'ordering': ['staff', 'subject'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('staff', 'subject', 'device_type'), name='unique_active_qualification')],
            },
        ),
    ]
