# Generated by Django 6.0.7 on 2026-09-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_subject_section_subject_instructorqualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorqualification',
            name='device_type',
            field=models.CharField(choices=[('CLASS', 'Аудиторные занятия'), ('FFS', 'Комплексный тренажер (FFS)'), ('FTD', 'Процедурный тренажер (FTD)'), ('CBT', 'Компьютерное обучение (CBT)'), ('ON_JOB', 'Стажировка на рабочем месте'), ('VR', 'VR-тренировки'), ('ASP_W', 'АСП вода'), ('ASP_L', 'АСП суша')], default='CLASS', help_text='На каком оборудовании/формате может преподавать', max_length=20, verbose_name='Тип средства обучения'),
        ),
    ]
